services:
  - docker

jobs:
  include:
    - stage: build
      script: make build-rnaseq-star-align
      script: make build-rnaseq
    - stage: validate
      script: make validate-rnaseq-star-align
      script: make validate-rnaseq

env:
  global:


