services:
  - docker

stages:
- name: build
- name: publish
  if: branch = master
- name: publish-staging
  if: branch != master
jobs:
  include:
  - stage: build
    name: Build
    script:
    - make build
    - make validate
  - stage: publish-staging
    name: Publish staging image
    script:
    - docker login -u="$QUAY_USERNAME" -p="$QUAY_PASSWORD" quay.io
    - make build
    - make publish
  - stage: publish
    name: Publish production image
    script: make publish-release
env:
  global:
  - secure: F0g989RjfXB83cpip6GdMTU09xqQn0F3V+MianQDGYxR4Ba9qMjl9eke4f/eSpepSw3+nnh63gguRHA886pWaECP3lzKNROP7vkflLUg+DjsatMOk/vWtZ8mtqqmT9Wl50hu7dgQoQzFtAbyvA8MDkeo9sNvZOr5GOcWkr3irDMpNZ7tMrpML1PvYfoXOZW8Q5K0lRlB2HHvwU9pXT20JARGzJJc5df+qKKieWSr/oFVmu4a/EH9ISjE0NN3dS80HiX7sAzeQE/k7Y3zhrTUiwCciuRh8fcWDNrbyU2n9qLO6vq6jjoLAGbQOOjJxLOXnr0EGSkE8cZHfPwqSwPbzEA+7/scJjxCixp6d88qh80MLV3L2ZYRctqtNo+i1gPXtoM72qQ1SRo9tvrNBZ4eSd9m2J5l+ElhFekEJ/4t1Dv/g4rIO4yKHMKvARd0q+/3xZ0U7Usw/Jm/EJsReyRW+97i7Lte1uAyC7euyGAmet7ksZIFdAsJUoh+kEMJm+wwLhW+pCJRiMCpeFCepZhygVpZA3y3ipUYS/vDji09joaTmA7d0enLO2+gGVQro1PqbtcG6ad6tjFU3PXVV3bBmwXEL4E7lHPLzPkwS4+AEKcqleelC23PI1rSnr4YkuXPSXxh9HdUVyDAX1mzU3vWgKZ3shxtDDIJozqnQgDtgr4=
  - secure: xtWHlOxTvmhz41oFtz1mhQbKmybhUO6RRMxtHDhU2kVbC14uLQ73stTPRnBbFaa6Gi5edO0l3cvnvur7Mk5tjL+f8TkEL6iuoNWea7butrCEtF6fsN0g0Sn3ihiA7RscdZuWWFfLWq0UAQdWN07JCa8TS4SLCXWBbxtiOKSJoz8rmN7ACUdrR+cxYoXP8VD5jTuTK+pKtvoXrlVlZNtoJBZFx9eeWABmgYfIfhJqn5zt2NvJzSL44LQ605r35omGVirxAZNWosm6HhFAl56jypvhR5skr8lzSk/+iGetihxwqsqSiFuczb3xkCQvefAR23tx6S1efUe0nuPuVolRiWNrRfUjyjCJUzwh/PSpARJH49NpmZ/V7ZocNcFGCEYzpQvKS2vmiYQhvxHTEVW5T1gZHOo+juNsED56CrdEBAJ9eoSlR1r7t1IZda57Nfid9mzaOPjkQ6Qx//KD1USR82rqf24ipzquTKyTNJOZmWF6Qmy98Yt7lfq9p46na1MDmu5fWJx9enWRDzBYL/p5EOCwleuRqeLCFwrMKJIwNEhB90nxNy95MxJXkblyQD9Eq3TobPVHh+cajHIPOYLg8MtFv1LESKxgjA79YohRxLb9TCA0bRhEojj0bP3OVR6cmE2XzqoXAk1s0sBvW4GDjQer3SB0OqwORRDUvOeGRn0=
