services:
  - docker

script:
 - make build-rnaseq-star-align
 - make build-gdc-rnaseq
 - make validate-rnaseq-star-align
 - make validate-gdc-rnaseq

stages:
 - build
 - test
 - name: publish
   if: branch = master
 - name: publish-staging
   if: branch != master

jobs:
  include:
  - name: "RNASeq Star Align"
   - stage: build
     script: make build-rnaseq-star-align
   - stage: publish-staging
     name: "Publish staging image"
     script: make publish--rnaseq-star-align
   - stage: publish
     name: "Publish production image"
     script: make publish-release-rnaseq-star-align
   - stage: test
     name: "Validate CWL"
     script: make validate-rnaseq-star-align

env:
  global:


