services:
  - docker

stages:
 - name: test
 - name: publish
   if: branch = master
 - name: publish-staging
   if: branch != master

jobs:
  include:
   - stage: test
     name: "Build and test rnaseq-star-align"
     script: 
     - make build-rnaseq-star-align
     - make validate-rnaseq-star-align
   - stage: publish-staging
     name: "Publish staging image"
     script: make publish-rnaseq-star-align
   - stage: publish
     name: "Publish production image"
     script: make publish-release-rnaseq-star-align

env:
  global:


